name       : glade
version    : 3.38.1
release    : 16
source     :
    - https://download.gnome.org/sources/glade/3.38/glade-3.38.1.tar.xz : 171a50be4930d4806fc8ce7f5ce3a75b49e9916f9d3037a5b50d35799bd0cfcd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
homepage   : https://glade.gnome.org/
summary    : Glade User Interface Tool
description: |
    Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %meson_configure -Dman=false
build      : |
    %ninja_build
install    : |
    %ninja_install
