name       : glade
version    : 3.18.3
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/glade/3.18/glade-3.18.3.tar.xz : ecdbce46e7fbfecd463be840b94fbf54d83723b3ebe075414cfd225ddab66452
license    : GPL-2.0
homepage   : https://glade.gnome.org/
summary    : Glade User Interface Tool
description: |
    Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    CONFIG_SHELL=/bin/bash %configure --disable-man-pages
build      : |
    %make
install    : |
    %make_install
