name       : glade
version    : 3.22.2
release    : 14
source     :
    - https://download.gnome.org/sources/glade/3.22/glade-3.22.2.tar.xz : edefa6eb24b4d15bd52589121dc109bc08c286157c41288deb74dd9cc3f26a21
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
homepage   : https://glade.gnome.org/
summary    : Glade User Interface Tool
description: |
    Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure --disable-man-pages
build      : |
    %make
install    : |
    %make_install
