name       : glade
version    : 3.20.2
release    : 8
source     :
    - https://ftp.gnome.org/pub/gnome/sources/glade/3.20/glade-3.20.2.tar.xz : 07d1545570951aeded20e9fdc6d3d8a56aeefe2538734568c5335be336c6abed
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.tools
homepage   : https://glade.gnome.org/
summary    : Glade User Interface Tool
description: |
    Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure --disable-man-pages
build      : |
    %make
install    : |
    %make_install
