name       : glade
version    : 3.20.0
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/glade/3.20/glade-3.20.0.tar.xz : 82d96dca5dec40ee34e2f41d49c13b4ea50da8f32a3a49ca2da802ff14dc18fe
license    : GPL-2.0
homepage   : https://glade.gnome.org/
summary    : Glade User Interface Tool
description: |
    Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure --disable-man-pages
build      : |
    %make
install    : |
    %make_install
