name       : glade
version    : 3.20.4
release    : 9
source     :
    - https://ftp.acc.umu.se/pub/gnome/sources/glade/3.20/glade-3.20.4.tar.xz : 4b82dfe635165b996ed75f95742bce788be8c8a45bf75c81892e3519902635d9
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.tools
homepage   : https://glade.gnome.org/
summary    : Glade User Interface Tool
description: |
    Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure --disable-man-pages
build      : |
    %make
install    : |
    %make_install
